### ISSUE TITLE
下载相应jetbrains包导入后，发现无法自动弹出工具助手

### ISSUE THREAD

**Issue by frankcgq105** [nickchou/jetbrains-agent#1]
GOLAND版本为：2020.1.2
请问大概是哪方面问题？

**Comment by nickchou** [comment]
你指的工具助手是什么，破解没问题吧 ？我并不是这个破解包的作者哈，我只是转发一下agent包。最近下载包被封得厉害

**Comment by frankcgq105** [comment]
OK,没问题了，操作失误，多谢关注。
