### ISSUE TITLE
RAR文件无法解压

### ISSUE THREAD

**Issue by csby** [nickchou/jetbrains-agent#2]
解压RAR文件（jetbrains-agent-2020.1.2.rar）时提示文件已损坏，

**Comment by csby** [comment]
建议放到Release下面

**Comment by nickchou** [comment]
你这个建议可以，下次我放Release。你没法解压吗，留个邮箱我发你，主要是百度云盘等封得厉害，没地放了。

**Comment by csby** [comment]
> 你这个建议可以，下次我放Release。你没法解压吗，留个邮箱我发你，主要是百度云盘等封得厉害，没地放了。

可以加压了。之前是我用RAR版本太低的原因，用最新版本的RAR已经能正常解压了，谢谢！
